#!/usr/bin/env sh

# Variables and script settings
divider="--------------"

# User defined variables
clear
while : ; do
	printf 'Are you installinst on Arch or Artix?'
	read -r OS
	case $OS in
		[Aa][Rr][Cc][Hh]) OS="arch" ;;
		[Aa][Rr][Tt][Ii][Xx]) OS="artix" ;;
		*) printf 'Please answer either Arch or Artix' ;;
	esac
done


printf "\n$divider"
while : ; do
	printf "\nDo you prefer vim or nano as a text editor?"
	read -r editor
	case $editor in
		[Vv][Ii][Mm]) pacman --needed --noconfirm -Sy vim; editor="vim" ;;
		[Nn][Aa][Nn][Oo]) editor="nano" ;;
		*) printf 'Please answer either vim or nano' ;;
	esac
done

printf "\n$divider"
while : ; do
	printf "\nAre you installing on a Bios or a Efi machine?"
	read -r bios
	case $bios in
		[Bb][Ii][Oo][Ss]) bios="bios" ;;
		[Ee][Ff][Ii]) bios="efi" ;;
		*) printf 'Pease answer Bios or Efi' ;;
	esac
done

# Configure and format partitions
printf "\n$divider"
while : ; do
	printf "Would you like to configure the drives yourself or completely wipe the drive and do a complete (re)install? [Configure/Auto]"
	read -r auto
	case $auto in
		[Cc][Oo][Nn][Ff][Ii][Gg][Uu][Rr][Ee]) auto="configure" ;;
		[Aa][Uu][Tt][Oo]) auto="auto" ;;
		*) printf 'Please answer either Configure or Auto' ;;
	esac
done

# Give tips and a zsh menu for self
# user configuration
if [ "$auto" = "configure" ]; then
	printf "\n$divider"
	[ $bios = "bios" ] && printf "\nIf you're going to (re)install grub, mount your boot partition at /mnt/boot"
	[ $bios = "efi" ] && printf "\nIf you're going to (re)install grub, mount your boot partition at /esp"
	printf 'General rule of thumb, root partition is mounted at /mnt'
	printf 'and home pertition (if you have one) is mounted at /mnt/home'
	zsh
	wait

	clear
	echo "Please select the drive you would like to install $OS to:"
	sdrive="$(echo "$(lsblk -lp | grep "disk $" | awk '{print $1, "("$4")"}')" | umenu)"
	cdrive=$(echo "$sdrive" | awk '{print $1}')
elif [ "$auto" = "auto" ]; then
	clear
	echo "Please select the drive you would like to install $OS to:"
	sdrive="$(echo "$(lsblk -lp | grep "disk $" | awk '{print $1, "("$4")"}')" | umenu)"
	cdrive=$(echo "$sdrive" | awk '{print $1}')

	printf "\n$divider"
	while : ; do
		printf 'How big do you want your root partition to be? (30gb,50gb,etc)'
		read -r rps
		while ! echo "$rps" | grep -o "[0-9]+[[Aa]-[Zz]]"; do
			printf 'Not acceptable size!'
			printf 'How big do you want your root partition to be? (30gb,50gb,etc)'
			read -r rps
		done
	done

	printf "\n$divider"
	while : ; do
		printf "\nDo you want a swap partition? [y/N]"
		read -r ssp
		case $ssp in
			[Yy]) \
 			ssp="y"
			printf 'How big do you want your swap patition? Usually 1.5x your ram'
			read -r sps
			while ! echo "$sps" | grep -o "[0-9]+[[Aa]-[Zz]]"; do
				printf 'Not acceptable size!'
				printf 'How big do you want your swap patition? Usually 1.5x your ram'
				read -r rps
			done

		esac
	done

	[ "$bios" = "bios" ] && \
		printf "\n$divider"
		while : ; do
			printf 'Do you want a dos or a gpt partition scheme? [dos/gpt]'
			read -r ps
			case $ps in
				[Dd][Oo][Ss]) ps="dos" ;;
				[Gg][Pp][Tt]) ps="gpt" ;;
				*) printf "Unkown or unsupported partition scheme, please answer either 'dos' or 'gpt'" ;;
			esac
		done

	# Big O'l code block for auto partitioning
	# using the partitioner script.
	dd if=/dev/zero of="$cdrive"  bs=512  count=1
	if [ "$bios" = "efi" ] && [ "$ssp" != "y" ]; then
		sh ~/tart/partitioner gns $cdrive 500mb $rps
		mkfs.fat -F32 "$cdrive"1
		mount "$cdrive"1 /esp
	elif [ "$bios" = "efi" ] && [ "$ssp" = "y" ]; then
		sh ~/tart/partitioner gs $cdrive 500mb $rps $sps
		mkfs.fat -F32 "$cdrive"1
		mount "$cdrive"1 /esp
		mkswap "$cdrive"2
		swapon "$cdrive"2
	elif [ "$bios" = "bios" ] && [ "$ssp" != "y" ] && [ "$ps" = "dos" ]; then
		sh ~/tart/partitioner dns $cdrive 500mb $rps
		mkfs.ext4 "$cdrive"1
		mkdir /mnt/boot
		mount "$cdrive"1 /mnt/boot
	elif [ "$bios" = "bios" ] && [ "$ssp" = "y" ];  || [ "$ps" = "dos" ]then
		sh ~/tart/partitioner ds $cdrive 500mb $rps $sps
		mkfs.ext4 "$cdrive"1
		mkdir /mnt/boot
		mount "$cdrive"1 /mnt/boot
		mkswap "$cdrive"2
		swapon "$cdrive"2
	elif [ "$bios" = "bios" ] && [ "$ssp" != "y" ] && [ "$ps" = "gpt" ]; then
		sh ~/tart/partitioner gns $cdrive 500mb $rps
		mkfs.ext4 "$cdrive"1
		mkdir /mnt/boot
		mount "$cdrive"1 /mnt/boot
	elif [ "$bios" = "bios" ] && [ "$ssp" = "y" ];  || [ "$ps" = "gpt" ]then
		sh ~/tart/partitioner gs $cdrive 500mb $rps $sps
		mkfs.ext4 "$cdrive"1
		mkdir /mnt/boot
		mount "$cdrive"1 /mnt/boot
		mkswap "$cdrive"2
		swapon "$cdrive"2

	fi
	mkfs.ext4 "$cdrive"3
	mkfs.ext4 "$cdrive"4
	mount "$cdrive"3 /mnt
	mkdir /mnt/home
	mount "$cdrive"4 /mnt/home
fi

# Mirrorlist || Init System
printf "\n$divider"
case $OS in
	Arch) \
	printf "\nThe Arch mirror list can be slow and unreliable, please edit the mirrorlist for faster speeds. Press Enter to continue..."
	read tmp >/dev/null
	$editor /etc/pacman.d/mirrorlist ;;
	Artix) \
	printf "\nWhich init system would you like to install? [Openrc/Runit/s6]"
	read -r init
	case $init in
		[Oo][Pp][Ee][Nn][Rr][Cc]) init="openrc" ;;
		[Rr][Uu][Nn][Ii][Tt]) init="runit" ;;
		[Ss]6) init="s6" ;;
		*) printf 'Please answer either Openrc, Runit, or s6' ;;
	esac
esac

# Install
clear
case $OS in
	arch) pacstrap /mnt linux linux-firmware base dash $editor ;;
	artix) case $init in
		openrc) basestrap /mnt linux linux-firmware base elogind-openrc openrc dash $editor ;;
		runit) basestrap /mnt linux linux-firmware base elogind-runit runit dash $editor ;;
		s6) basestrap /mnt linux linux-firmware base elogind-s6 s6 dash $editor ;;
	esac ;;
esac

# Post Install
printf "\n$divider"
case $OS in
	arch)
	genfstab -U -p /mnt >> /mnt/etc/fstab

	export OS
	export bios
	export editor
	export cdrive

	cp ~/tart/tart-post-chroot /mnt
	arch-chroot /mnt dash tart-post-chroot
	rm /mnt/tart-post-chroot

	printf "\nWould you like to restart now? Y/n"
	read -r tmp
	case $tmp in
		n) exit ;;
		*) reboot ;;
	esac
	;;

	artix)
	fstabgen -U -p /mnt >> /mnt/etc/fstab

	export OS
	export bios
	export editor
	export cdrive
	export init

	cp ~/tart/tart-post-chroot /mnt
	artools-chroot /mnt dash tart-post-chroot
	rm /mnt/tart-post-chroot

	printf "\nWould you like to restart now? Y/n"
	read tmp
	case $tmp in
		n) exit ;;
		*) reboot ;;
	esac
	;;
esac
